.Show Info: &environment_information
  build-aux/ci/ci-helper.sh "INFO" &&
  build-aux/ci/ci-helper.sh "GIT_INFO"

include:
 - project: Infrastructure/freedesktop-ci-templates
   file: templates/fedora.yml
   ref: aec7a6ce7bb38902c70641526f6611e27141784a
 - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
   inputs:
     dist-job-name: build-gnomeos
 - project: GNOME/citemplates
   file: templates/default-rules.yml
 - component: "gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master"
   inputs:
     before-script: *environment_information
     meson-options: "-Ddocumentation=true -Dmalcontent=true $MESON_SETUP_ARGS"
     meson-test-options: "--verbose"
     lsan-options: "suppressions=${CI_PROJECT_DIR}/build-aux/ci/lsan.supp"
 # Build with only default options, we don't run tests for this one
 - component: "gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master"
   inputs:
     job-name: "build-gnomeos-default-options"
     before-script: *environment_information
     meson-options: "$MESON_SETUP_ARGS"
     run-tests: "no"
     grcov-c: "disabled"
     scan-build: "disabled"
     goblint: "disabled"

variables:
  FDO_UPSTREAM_REPO: gnome/gnome-control-center
  MESON_BUILD_DIR: _build
  MESON_SETUP_ARGS: "--fatal-meson-warnings --werror -Dwarning_level=2"

stages:
  - prepare
  - build
  - test
  - manual
  - deploy

.Build Logs: &build_logs
  name: build_logs
  when: always
  paths:
    - ./*.log
    - $MESON_BUILD_DIR/meson-logs/

.Build Output: &build_output
  artifacts:
    name: build_output
    when: always
    paths:
      - ./*.log
      - $MESON_BUILD_DIR/
    expire_in: 3h30min

.Build Procedure: &build_procedure
  echo "== Building ==" &&
  meson setup $MESON_BUILD_DIR ${BUILD_OPTS} $MESON_SETUP_ARGS &&
  meson compile -C $MESON_BUILD_DIR 2>&1 | tee compilation.log

.Run Tests: &run_tests
  export GSK_RENDERER=gl &&
  echo "== Testing ==" &&
  meson test -C $MESON_BUILD_DIR --verbose --no-stdsplit --no-rebuild

.fedora.container.common:
  variables:
    # When branching a stable release, change 'main' to the
    # release branch name to ensure that a new image will
    # be created, tailored for the stable branch.
    # Should probably also switch away from 'rawhide',
    # to stable fedora branch as well.
    BRANCH_NAME: 'main'
    CONTAINER_TAG: '2026-04-17.1'
    FEDORA_VERSION: rawhide
    # Derive FDO variables from this automatically.
    # DO NOT edit, instead change the variables above
    FDO_REPO_SUFFIX: '${BRANCH_NAME}'
    FDO_DISTRIBUTION_TAG: '${CONTAINER_TAG}-fedora-${FEDORA_VERSION}'
    FDO_DISTRIBUTION_VERSION: '${FEDORA_VERSION}'

#############################################
#          Create CI Docker Images          #
#############################################

# See also https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates
build.container.fedora@x86_64:
  extends:
  - '.fdo.container-build@fedora'
  - '.fedora.container.common'
  stage: 'prepare'
  variables:
    # no need to pull the whole tree for rebuilding the image
    GIT_STRATEGY: none
    # Expiry sets fdo.expires on the image
    FDO_EXPIRES_AFTER: 8w
    # NOTES:
    # - most packages are needed for testing
    # - glibc-langpack-en is needed for sorting in run-style-check-diff.sh
    # - libsass-devel, sassc are often needed for building libadwaita, gtk, etc.
    # - libsoup3-devel required for malcontent is not included in its build depends yet
    FDO_DISTRIBUTION_PACKAGES: >-
      dnf5-plugins
      gawk
      git
      meson
      glibc-langpack-en
      python3-dbusmock
      xorg-x11-server-Xvfb
      mesa-dri-drivers
      libsass-devel sassc
      libsoup3-devel
    FDO_DISTRIBUTION_EXEC: |-
      dnf builddep -y gnome-control-center && \
      dnf builddep -y gsettings-desktop-schemas && \
      dnf builddep -y gtk4 && \
      dnf builddep -y gnome-settings-daemon && \
      dnf builddep -y libadwaita && \
      dnf builddep -y gnome-online-accounts && \
      dnf builddep -y malcontent && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git && \
        cd gsettings-desktop-schemas && \
        meson setup $MESON_BUILD_DIR --prefix=/usr && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/gtk.git && \
        cd gtk && \
        meson setup $MESON_BUILD_DIR --prefix=/usr -Dintrospection=enabled && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-settings-daemon.git && \
        cd gnome-settings-daemon && \
        meson setup $MESON_BUILD_DIR --prefix=/usr && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/libadwaita.git && \
        cd libadwaita && \
        meson setup $MESON_BUILD_DIR --prefix=/usr -Dtests=false -Dexamples=false && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-online-accounts.git && \
        cd gnome-online-accounts && \
        meson setup $MESON_BUILD_DIR --prefix=/usr -Dfedora=true  && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/blueprint-compiler.git && \
        cd blueprint-compiler && \
        meson setup $MESON_BUILD_DIR --prefix=/usr && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-desktop.git && \
        cd gnome-desktop && \
        meson subprojects download && \
        meson setup $MESON_BUILD_DIR --prefix=/usr -Ddesktop_docs=false -Dintrospection=true -Dqr=enabled && \
        meson compile -C $MESON_BUILD_DIR && \
        meson install -C $MESON_BUILD_DIR && \
        cd .. && \
      dnf remove -y systemtap-runtime

##
# Stage: Build
#
# Checks if GNOME Control Center is properly building and installing. This is the
# most important stage of the CI, and no MR should ever be merged if it breaks
# any of them.
##
build:
  extends:
    - '.fdo.suffixed-image@fedora'
    - '.fedora.container.common'
  stage: build

  script:
    - *environment_information
    - *build_procedure

    - echo "== Installing =="
    - meson install -C $MESON_BUILD_DIR

    - echo "== Report =="
    - build-aux/ci/ci-helper.sh "WARNINGS"

  <<: *build_output

  except:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"

# Same as build but with various off-by-default options enabled
conditional builds:
  extends:
    - build
  allow_failure: true
  artifacts:
    # Only save build logs for these
    <<: *build_logs
  parallel:
    matrix:
      - BUILD_OPTS: '-Dmalcontent=true'
      - BUILD_OPTS: '-Ddocumentation=true'

##
# Stage: Test
#
# Runs static checks.
# Runs the unit tests.
##
style-check-diff:
  extends:
  - '.fdo.suffixed-image@fedora'
  - '.fedora.container.common'
  needs:
  - build.container.fedora@x86_64
  stage: test
  when: always
  allow_failure: true
  script:
    - .gitlab-ci/run-style-check-diff.sh

check-potfiles:
  extends:
  - '.fdo.suffixed-image@fedora'
  - '.fedora.container.common'
  needs:
  - build.container.fedora@x86_64
  stage: test
  when: always
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - .gitlab-ci/check-potfiles.sh

test:
  extends:
    - '.fdo.suffixed-image@fedora'
    - '.fedora.container.common'
  stage: test

  needs:
    - build

  script:
    - *environment_information
    - *run_tests

  artifacts:
    <<: *build_logs
    reports:
        junit: '$MESON_BUILD_DIR/meson-logs/testlog.junit.xml'

  except:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"
      - $CI_COMMIT_TITLE =~ /^Update.*translation$/

##
# Stage: Deploy
#
# Publishes release artifacts and the Coverage Report generated above
##
pages:
  stage: deploy
  dependencies:
    - build-gnomeos-grcov-c
  script:
    - mv public_grcov/ public/
  artifacts:
    paths:
      - public
  only:
    - main@GNOME/gnome-control-center

  except:
    variables:
      - $CRON_TASK == "BUILD_CI_IMAGES"
      - $CI_COMMIT_TITLE =~ /^Update.*translation$/
