/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("Use GNOME for setting background");
gchar *s = N_("Colors");
gchar *s = N_("Effect");
gchar *s = N_("Primary color");
gchar *s = N_("Right or bottom color");
gchar *s = N_("Pick a color");
gchar *s = N_("Pick a color");
gchar *s = N_("Solid Color");
gchar *s = N_("Vertical Gradient");
gchar *s = N_("Horizontal Gradient");
gchar *s = N_("Apply changes automatically");
gchar *s = N_("Wallpaper");
gchar *s = N_("File");
gchar *s = N_("Display Style");
gchar *s = N_("Tiled");
gchar *s = N_("Centered");
gchar *s = N_("Scaled (keep aspect ratio)");
gchar *s = N_("Stretched (change aspect ratio)");
gchar *s = N_("Browse...");
gchar *s = N_("(None)");
gchar *s = N_("Adjust wallpaper's transparency");
gchar *s = N_("More Transparent");
gchar *s = N_("More Solid");
