/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Color");
gchar *s = N_("Color 1");
gchar *s = N_("Color 2");
gchar *s = N_("Pick a color");
gchar *s = N_("Pick a color");
gchar *s = N_("Solid");
gchar *s = N_("Gradient");
gchar *s = N_("Vertical");
gchar *s = N_("Horizontal");
gchar *s = N_("Wallpaper");
gchar *s = N_("Tiled");
gchar *s = N_("Centered");
gchar *s = N_("Scaled (keep aspect)");
gchar *s = N_("Scaled");
gchar *s = N_("Disable background selection");
