/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Menu Options");
gchar *s = N_("Can detach and move menus");
gchar *s = N_("Menus have relieved border");
gchar *s = N_("Submenus can be torn off");
gchar *s = N_("Menu items have icons");
gchar *s = N_("Statusbar Options");
gchar *s = N_("Statusbar is interactive when possible");
gchar *s = N_("Statusbar progress meter is on the right");
gchar *s = N_("Toolbar Options");
gchar *s = N_("Can detach and move toolbars");
gchar *s = N_("Toolbars have relieved border");
gchar *s = N_("Toolbar buttons have relieved border");
gchar *s = N_("Toolbars have line separators");
gchar *s = N_("Toolbars have text labels");
gchar *s = N_("window2");
gchar *s = N_("Dialog Layout");
gchar *s = N_("Dialog Buttons:");
gchar *s = N_("Default value\n"
              "Spread buttons out\n"
              "Put buttons on edges\n"
              "Left-justify buttons\n"
              "Right-justify buttons\n"
              "");
gchar *s = N_("Dialog buttons have icons");
gchar *s = N_("Use statusbar instead of dialog when possible");
gchar *s = N_("Dialog Behavior");
gchar *s = N_("Dialog position:");
gchar *s = N_("Dialog hints:");
gchar *s = N_("Let window manager decide\n"
              "Center of the screen\n"
              "At the mouse pointer\n"
              "");
gchar *s = N_("Dialogs are like other windows\n"
              "Dialogs are treated specially by the window manager\n"
              "");
gchar *s = N_("Place dialogs over application window when possible");
gchar *s = N_("window3");
gchar *s = N_("GNOME MDI Options");
gchar *s = N_("Default MDI Mode:");
gchar *s = N_("MDI notebook tab position:");
gchar *s = N_("Notebook\n"
              "Toplevel\n"
              "Modal\n"
              "");
gchar *s = N_("Left\n"
              "Right\n"
              "Top\n"
              "Bottom\n"
              "");
