/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Restore all tools");
gchar *s = N_("View Logs...");
gchar *s = N_("Advanced...");
gchar *s = N_("Restore only");
gchar *s = N_("Restore configuration from");
gchar *s = N_("days ago");
gchar *s = N_("Configuration Restoration");
gchar *s = N_("Create...");
gchar *s = N_("Destroy...");
gchar *s = N_("Rename...");
gchar *s = N_("Change to this Location");
gchar *s = N_("Edit this Location");
gchar *s = N_("Location Management");
gchar *s = N_("Restore old configuration");
gchar *s = N_("Restore configuration from");
gchar *s = N_("days ago");
gchar *s = N_("Restore all tools");
gchar *s = N_("Restore only");
gchar *s = N_("View Logs...");
gchar *s = N_("Advanced...");
