/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Launch control panels in separate windows");
gchar *s = N_("Put control panels in the control center's window");
gchar *s = N_("Display control panels as HTML");
gchar *s = N_("Display control panels as a set of icons");
gchar *s = N_("Display control panels as a tree");
gchar *s = N_("Browse with single window");
gchar *s = N_("Browse with multiple windows");
gchar *s = N_("Appearance");
gchar *s = N_("New-control-center");
gchar *s = N_("HTML");
gchar *s = N_("Icon List");
gchar *s = N_("Tree");
