/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Enable");
gchar *s = N_("Enable sound server startup");
gchar *s = N_("Sounds for events");
gchar *s = N_("General");
gchar *s = N_("Event");
gchar *s = N_("File to Play");
gchar *s = N_("Sound Events");
