FROM arm64v8/fedora:30
MAINTAINER Claudio André (c) 2018 V1.0

LABEL architecture="aarch64"
LABEL version="1.0"
LABEL description="Multiarch Docker image to run CI for GNOME Settings."

ADD x86_64_qemu-aarch64-static.tar.gz /usr/bin

RUN dnf -y --nogpgcheck upgrade && \
    dnf -y install \
                   @c-development @development-tools clang libasan gcovr \
                   accountsservice-devel cheese-libs-devel chrpath colord-devel  \
                   colord-gtk-devel cups-devel desktop-file-utils docbook-style-xsl flatpak-devel gdk-pixbuf2-devel \
                   gettext git glib2-devel gnome-bluetooth-libs-devel gnome-desktop3-devel \
                   gnome-online-accounts-devel gnome-settings-daemon-devel grilo-devel \
                   gsettings-desktop-schemas-devel gsound-devel gtk3-devel ibus-devel intltool libcanberra-devel \
                   libgtop2-devel libgudev-devel libnma-devel libpwquality-devel libsmbclient-devel \
                   libsoup-devel libudisks2-devel libwacom-devel libX11-devel libXi-devel libxml2-devel libxslt \
                   meson ModemManager-glib-devel NetworkManager-libnm-devel \
                   polkit-devel pulseaudio-libs-devel upower-devel \
                   python3-dbusmock xorg-x11-server-Xvfb mesa-dri-drivers libsecret-devel && \
     dnf -y clean all

CMD ["/bin/bash"]

