/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Auto-repeat");
gchar *s = N_("Enable auto-repeat");
gchar *s = N_("Repeat rate");
gchar *s = N_("Repeat delay");
gchar *s = N_("Keyboard click");
gchar *s = N_("Click on keypress");
gchar *s = N_("Click volume");
gchar *s = N_("Preview");
gchar *s = N_("Test settings");
