/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Twist:");
gchar *s = N_("Low");
gchar *s = N_("High");
gchar *s = N_("Twist speed:");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Wobble:");
gchar *s = N_("Low");
gchar *s = N_("High");
gchar *s = N_("Size:");
gchar *s = N_("Small");
gchar *s = N_("Large");
