/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Sharp turns");
gchar *s = N_("Truchet lines");
gchar *s = N_("Speed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Timeout");
gchar *s = N_("Small");
gchar *s = N_("Large");
gchar *s = N_("Random");
gchar *s = N_("Specific");
gchar *s = N_("number of Ants");
gchar *s = N_("Random size upto");
gchar *s = N_("Specific size of");
gchar *s = N_("Number of colours");
gchar *s = N_("Two");
gchar *s = N_("Many");
gchar *s = N_("Randomize");
gchar *s = N_("Three Sided cells");
gchar *s = N_("Four Sided cells");
gchar *s = N_("Six Sided cells");
gchar *s = N_("Nine Sided cells");
gchar *s = N_("Twelve Sided cells");
gchar *s = N_("Monochrome");
gchar *s = N_("Full Color");
