/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Balls");
gchar *s = N_("Lines");
gchar *s = N_("Tails");
gchar *s = N_("Polygons");
gchar *s = N_("Splines");
gchar *s = N_("Threshold of repulsion");
gchar *s = N_("Small");
gchar *s = N_("Large");
gchar *s = N_("Length of Trail");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("Speed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Full Color");
gchar *s = N_("Monochrome");
gchar *s = N_("Number of Colors");
gchar *s = N_("Color Contrast");
gchar *s = N_("Low");
gchar *s = N_("High");
