/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Speed of rotation.");
gchar *s = N_("Faster");
gchar *s = N_("Slower");
gchar *s = N_("Speed of the 90 degree rotation.");
gchar *s = N_("Faster");
gchar *s = N_("Slower");
gchar *s = N_("Display screensaver in monochrome.");
