/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Speed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Full Color");
gchar *s = N_("Monochrome");
