/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Speed of Motion.");
gchar *s = N_("Faster");
gchar *s = N_("Slower");
gchar *s = N_("Draw circles instead of pixmap bubbles.");
gchar *s = N_("Don't hide bubbles when they pop.");
gchar *s = N_("Bubbles exist in three dimensions.");
gchar *s = N_("Display screensaver in monochrome.");
