/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Density");
gchar *s = N_("Denser");
gchar *s = N_("Thinner");
gchar *s = N_("Number of seeds");
gchar *s = N_("Seeds");
gchar *s = N_("Speed of Motion.");
gchar *s = N_("Faster");
gchar *s = N_("Slower");
