/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Time between redraws:");
gchar *s = N_("seconds");
gchar *s = N_("Use color when drawing.");
gchar *s = N_("Cycle through colors.");
