/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Text for flag");
gchar *s = N_("Bitmap for flag");
gchar *s = N_("Speed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Timeout");
gchar *s = N_("Small");
gchar *s = N_("Large");
gchar *s = N_("Random size up to");
gchar *s = N_("Specific size of");
gchar *s = N_("Number of colours");
gchar *s = N_("Two");
gchar *s = N_("Many");
gchar *s = N_("Full Color");
gchar *s = N_("Monochrome");
