/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Number of Colors.");
gchar *s = N_("Colors:");
gchar *s = N_("Number of planets to use.");
gchar *s = N_("Count:");
gchar *s = N_("Display screensaver in monochrome.");
gchar *s = N_("Orbit should decay.");
gchar *s = N_("Objects should leave trails behind them.");
