/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Duration of laser burst.");
gchar *s = N_("Shorter");
gchar *s = N_("Longer");
gchar *s = N_("Size of burst.");
gchar *s = N_("Segments:");
gchar *s = N_("Display screensaver in monochrome.");
