/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Delay between each step in the maze.");
gchar *s = N_("Less Delay");
gchar *s = N_("More Delay");
gchar *s = N_("Delay between drawing the maze and starting the solution.");
gchar *s = N_("Less Delay");
gchar *s = N_("More Delay");
gchar *s = N_("Delay between finishing the maze and starting a new one.");
gchar *s = N_("Less Delay");
gchar *s = N_("More Delay");
gchar *s = N_("Put a bridge over the logo?");
