/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Speed of Motion.");
gchar *s = N_("Faster");
gchar *s = N_("Slower");
gchar *s = N_("Use XOR drawing function.");
gchar *s = N_("Draw square at weird starting points.");
gchar *s = N_("Display screensaver in monochrome.");
