/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Time to show each picture.");
gchar *s = N_("Shorter");
gchar *s = N_("Longer");
gchar *s = N_("Maximum number of lines.");
gchar *s = N_("Less");
gchar *s = N_("More");
gchar *s = N_("Time to fade away.");
gchar *s = N_("Shorter");
gchar *s = N_("Longer");
gchar *s = N_("Display screensaver in monochrome.");
