/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Particles on screen");
gchar *s = N_("Count:");
gchar *s = N_("Frequency of missile launch");
gchar *s = N_("Slower");
gchar *s = N_("Faster");
gchar *s = N_("Number of particles");
gchar *s = N_("Less");
gchar *s = N_("More");
