/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Lines");
gchar *s = N_("Polygons");
gchar *s = N_("Number of points:");
gchar *s = N_("Discrete Lines");
gchar *s = N_("Solid Trails");
gchar *s = N_("Transparent Trails");
gchar *s = N_("XOR Trails");
gchar *s = N_("Trails attract each other");
gchar *s = N_("Speed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Length");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("Width");
gchar *s = N_("Narrow");
gchar *s = N_("Wide");
gchar *s = N_("Spread between lines");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("Number of trails:");
gchar *s = N_("Full Color");
gchar *s = N_("Monochrome");
gchar *s = N_("Color contrast");
gchar *s = N_("Low");
gchar *s = N_("High");
