/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Number of Iterations");
gchar *s = N_("Small");
gchar *s = N_("Large");
gchar *s = N_("Offset");
gchar *s = N_("Small");
gchar *s = N_("Large");
gchar *s = N_("With X-axis Symmetry");
gchar *s = N_("With Y-axis Symmetry");
gchar *s = N_("Delay before next redraw");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("Speed to clear the screen");
