/*
 * Translatable strings file generated by extract-labels
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Speed of animation.");
gchar *s = N_("Fast");
gchar *s = N_("Slow");
gchar *s = N_("Thickness of color bands (0 = Random)");
gchar *s = N_("Slim");
gchar *s = N_("Quickness of rotation at each step (0 = Random)");
gchar *s = N_("Slow");
gchar *s = N_("Duration of current shape.");
gchar *s = N_("Seconds");
gchar *s = N_("Use raw shapes ");
gchar *s = N_("Change to display in monochrome.");
