/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Mouse Configuration");
gchar *s = N_("My mouse is:");
gchar *s = N_("Left handed");
gchar *s = N_("Right handed");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Mouse speed:");
gchar *s = N_("Low");
gchar *s = N_("High");
gchar *s = N_("Sensitivity:");
