/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Mouse buttons");
gchar *s = N_("Left handed");
gchar *s = N_("Right handed");
gchar *s = N_("Mouse motion");
gchar *s = N_("Acceleration");
gchar *s = N_("Threshold");
gchar *s = N_("Slow");
gchar *s = N_("Fast");
gchar *s = N_("Large");
gchar *s = N_("Small");
